builds:
  - main: ./cmd/fitm
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
